apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kubernetes-development
  labels:
    k8s-app: kubernetes-development
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kubernetes-development
  template:
    metadata:
      labels:
        k8s-app: kubernetes-development
    spec:
      hostNetwork: true
      containers:
      - name: kubernetes-development
#        image: registry.bst-1.cns.bstjpc.com:5000/k8s-client-go:v1.10
#        image: registry.bst-1.cns.bstjpc.com:5000/k8s-dev:v1.10
#        image: registry.bst-1.cns.bstjpc.com:5000/debian:stretch-slim
#        image: registry.bst-1.cns.bstjpc.com:5000/flex-provisioner:20180529
#        image: registry.bst-1.cns.bstjpc.com:5000/k8s1-10-docker-1-38:180530
        image: registry.bst-1.cns.bstjpc.com:5000/docker-commit-push:20180530
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command:
          - bash
          - -c
          - "tail -f /dev/null"
        volumeMounts:
        - name: program
          mountPath: /go/src/k8s-dev
        - name: kubeconfig
          mountPath: /root/.kube
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: program
        hostPath:
          path: /data/lib/gopath/src/k8s-dev
      - name: kubeconfig
        hostPath:
          path: /root/.kube
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      serviceAccountName: default
      nodeSelector:
        kubernetes.io/hostname: k8s-m1