FROM registry.bst-1.cns.bstjpc.com:5000/k8s-dev:v1.10 as build

RUN mkdir -p /go/src/k8s-dev

COPY get-container-id /go/src/k8s-dev/get-container-id
COPY utils /go/src/k8s-dev/utils

WORKDIR /go/src/k8s-dev/get-container-id

RUN go build

FROM registry.bst-1.cns.bstjpc.com:5000/debian:stretch-slim

COPY --from=build /go/src/k8s-dev/get-container-id/get-container-id /usr/bin/get-container-id
COPY bin/docker /usr/bin/docker
COPY commit-job/run.sh /run.sh

RUN apt-get update && \
    apt-get install libltdl7 -y && \
    chmod +x /usr/bin/docker /usr/bin/get-container-id /run.sh

ENTRYPOINT /run.sh