FROM registry.cn-hangzhou.aliyuncs.com/mhc_dev/k8s-app-build-env:go-1.10 as build

COPY ingress-watcher /go/src/k8s-dev/ingress-watcher

WORKDIR /go/src/k8s-dev/ingress-watcher

RUN go build

FROM debian:stretch-slim

COPY --from=build /go/src/k8s-dev/ingress-watcher/ingress-watcher /usr/bin/ingress-watcher
COPY ingress-watcher/etcdctl /usr/bin/etcdctl