FROM registry.bst-1.cns.bstjpc.com:5000/k8s-dev:180612 as build

COPY ingress-watcher /go/src/k8s-dev/ingress-watcher

WORKDIR /go/src/k8s-dev/ingress-watcher

RUN go build

FROM registry.bst-1.cns.bstjpc.com:5000/debian:stretch-slim

COPY --from=build /go/src/k8s-dev/ingress-watcher/ingress-watcher /usr/bin/ingress-watcher
COPY ingress-watcher/etcdctl /usr/bin/etcdctl