apiVersion: v1
kind: Secret
metadata:
  name: minio-standalone-user
  labels:
    app: minio-standalone
type: Opaque
data:
  accesskey: "QUtJQUlPU0ZPRE5ON0VYQU1QTEU="
  secretkey: "d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ=="
