kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pv1
#  annotations:
#    volume.beta.kubernetes.io/storage-class: test-cephfs
spec:
  storageClassName: test-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
