apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs-flex-volume
provisioner: srcb.com/cephfs
parameters:
  monitors: 109.105.1.208:6789,109.105.1.209:6789,109.105.1.253:6789,109.105.1.254:6789,109.105.30.157:6789
  share: '/storage_class'
  authid: 'admin'
  mds: 'Data_Intelligence_Labfs'
  keyring: 'AQDeUgJbJgwNMhAAnzeW5LwQSwqMyWs7Zvl5cQ=='

