kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tesst-provisioner-1
spec:
  storageClassName: cephfs-flex-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tesst-provisioner-1
  labels:
    app: tesst-provisioner-1
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tesst-provisioner-1
    spec:
      containers:
      - image: registry.bst-1.cns.bstjpc.com:5000/clusterhq/fio-tool:latest
        name: fio
        command:
        - bash
        - -c
        - "tail -f /dev/null"
        volumeMounts:
        - name: fio-test-pv
          mountPath: /data
      volumes:
      - name: fio-test-pv
        persistentVolumeClaim:
          claimName: tesst-provisioner-1
